
//input ports
add mapped point in_clka in_clka -type PI PI
add mapped point in_clkb in_clkb -type PI PI
add mapped point in_restart in_restart -type PI PI
add mapped point in_direction_in[3] in_direction_in[3] -type PI PI
add mapped point in_direction_in[2] in_direction_in[2] -type PI PI
add mapped point in_direction_in[1] in_direction_in[1] -type PI PI
add mapped point in_direction_in[0] in_direction_in[0] -type PI PI

//output ports
add mapped point out_row_cathode[7] out_row_cathode[7] -type PO PO
add mapped point out_row_cathode[6] out_row_cathode[6] -type PO PO
add mapped point out_row_cathode[5] out_row_cathode[5] -type PO PO
add mapped point out_row_cathode[4] out_row_cathode[4] -type PO PO
add mapped point out_row_cathode[3] out_row_cathode[3] -type PO PO
add mapped point out_row_cathode[2] out_row_cathode[2] -type PO PO
add mapped point out_row_cathode[1] out_row_cathode[1] -type PO PO
add mapped point out_row_cathode[0] out_row_cathode[0] -type PO PO
add mapped point out_column_anode[7] out_column_anode[7] -type PO PO
add mapped point out_column_anode[6] out_column_anode[6] -type PO PO
add mapped point out_column_anode[5] out_column_anode[5] -type PO PO
add mapped point out_column_anode[4] out_column_anode[4] -type PO PO
add mapped point out_column_anode[3] out_column_anode[3] -type PO PO
add mapped point out_column_anode[2] out_column_anode[2] -type PO PO
add mapped point out_column_anode[1] out_column_anode[1] -type PO PO
add mapped point out_column_anode[0] out_column_anode[0] -type PO PO
add mapped point out_control_to_logic[1] out_control_to_logic[1] -type PO PO
add mapped point out_control_to_logic[0] out_control_to_logic[0] -type PO PO
add mapped point out_logic_to_control[1] out_logic_to_control[1] -type PO PO
add mapped point out_logic_to_control[0] out_logic_to_control[0] -type PO PO
add mapped point out_game_state[1] out_game_state[1] -type PO PO
add mapped point out_game_state[0] out_game_state[0] -type PO PO
add mapped point out_direction_state[1] out_direction_state[1] -type PO PO
add mapped point out_direction_state[0] out_direction_state[0] -type PO PO
add mapped point out_execution_state[1] out_execution_state[1] -type PO PO
add mapped point out_execution_state[0] out_execution_state[0] -type PO PO
add mapped point out_led_array_flat[63] out_led_array_flat[63] -type PO PO
add mapped point out_led_array_flat[62] out_led_array_flat[62] -type PO PO
add mapped point out_led_array_flat[61] out_led_array_flat[61] -type PO PO
add mapped point out_led_array_flat[60] out_led_array_flat[60] -type PO PO
add mapped point out_led_array_flat[59] out_led_array_flat[59] -type PO PO
add mapped point out_led_array_flat[58] out_led_array_flat[58] -type PO PO
add mapped point out_led_array_flat[57] out_led_array_flat[57] -type PO PO
add mapped point out_led_array_flat[56] out_led_array_flat[56] -type PO PO
add mapped point out_led_array_flat[55] out_led_array_flat[55] -type PO PO
add mapped point out_led_array_flat[54] out_led_array_flat[54] -type PO PO
add mapped point out_led_array_flat[53] out_led_array_flat[53] -type PO PO
add mapped point out_led_array_flat[52] out_led_array_flat[52] -type PO PO
add mapped point out_led_array_flat[51] out_led_array_flat[51] -type PO PO
add mapped point out_led_array_flat[50] out_led_array_flat[50] -type PO PO
add mapped point out_led_array_flat[49] out_led_array_flat[49] -type PO PO
add mapped point out_led_array_flat[48] out_led_array_flat[48] -type PO PO
add mapped point out_led_array_flat[47] out_led_array_flat[47] -type PO PO
add mapped point out_led_array_flat[46] out_led_array_flat[46] -type PO PO
add mapped point out_led_array_flat[45] out_led_array_flat[45] -type PO PO
add mapped point out_led_array_flat[44] out_led_array_flat[44] -type PO PO
add mapped point out_led_array_flat[43] out_led_array_flat[43] -type PO PO
add mapped point out_led_array_flat[42] out_led_array_flat[42] -type PO PO
add mapped point out_led_array_flat[41] out_led_array_flat[41] -type PO PO
add mapped point out_led_array_flat[40] out_led_array_flat[40] -type PO PO
add mapped point out_led_array_flat[39] out_led_array_flat[39] -type PO PO
add mapped point out_led_array_flat[38] out_led_array_flat[38] -type PO PO
add mapped point out_led_array_flat[37] out_led_array_flat[37] -type PO PO
add mapped point out_led_array_flat[36] out_led_array_flat[36] -type PO PO
add mapped point out_led_array_flat[35] out_led_array_flat[35] -type PO PO
add mapped point out_led_array_flat[34] out_led_array_flat[34] -type PO PO
add mapped point out_led_array_flat[33] out_led_array_flat[33] -type PO PO
add mapped point out_led_array_flat[32] out_led_array_flat[32] -type PO PO
add mapped point out_led_array_flat[31] out_led_array_flat[31] -type PO PO
add mapped point out_led_array_flat[30] out_led_array_flat[30] -type PO PO
add mapped point out_led_array_flat[29] out_led_array_flat[29] -type PO PO
add mapped point out_led_array_flat[28] out_led_array_flat[28] -type PO PO
add mapped point out_led_array_flat[27] out_led_array_flat[27] -type PO PO
add mapped point out_led_array_flat[26] out_led_array_flat[26] -type PO PO
add mapped point out_led_array_flat[25] out_led_array_flat[25] -type PO PO
add mapped point out_led_array_flat[24] out_led_array_flat[24] -type PO PO
add mapped point out_led_array_flat[23] out_led_array_flat[23] -type PO PO
add mapped point out_led_array_flat[22] out_led_array_flat[22] -type PO PO
add mapped point out_led_array_flat[21] out_led_array_flat[21] -type PO PO
add mapped point out_led_array_flat[20] out_led_array_flat[20] -type PO PO
add mapped point out_led_array_flat[19] out_led_array_flat[19] -type PO PO
add mapped point out_led_array_flat[18] out_led_array_flat[18] -type PO PO
add mapped point out_led_array_flat[17] out_led_array_flat[17] -type PO PO
add mapped point out_led_array_flat[16] out_led_array_flat[16] -type PO PO
add mapped point out_led_array_flat[15] out_led_array_flat[15] -type PO PO
add mapped point out_led_array_flat[14] out_led_array_flat[14] -type PO PO
add mapped point out_led_array_flat[13] out_led_array_flat[13] -type PO PO
add mapped point out_led_array_flat[12] out_led_array_flat[12] -type PO PO
add mapped point out_led_array_flat[11] out_led_array_flat[11] -type PO PO
add mapped point out_led_array_flat[10] out_led_array_flat[10] -type PO PO
add mapped point out_led_array_flat[9] out_led_array_flat[9] -type PO PO
add mapped point out_led_array_flat[8] out_led_array_flat[8] -type PO PO
add mapped point out_led_array_flat[7] out_led_array_flat[7] -type PO PO
add mapped point out_led_array_flat[6] out_led_array_flat[6] -type PO PO
add mapped point out_led_array_flat[5] out_led_array_flat[5] -type PO PO
add mapped point out_led_array_flat[4] out_led_array_flat[4] -type PO PO
add mapped point out_led_array_flat[3] out_led_array_flat[3] -type PO PO
add mapped point out_led_array_flat[2] out_led_array_flat[2] -type PO PO
add mapped point out_led_array_flat[1] out_led_array_flat[1] -type PO PO
add mapped point out_led_array_flat[0] out_led_array_flat[0] -type PO PO
add mapped point out_random_num[5] out_random_num[5] -type PO PO
add mapped point out_random_num[4] out_random_num[4] -type PO PO
add mapped point out_random_num[3] out_random_num[3] -type PO PO
add mapped point out_random_num[2] out_random_num[2] -type PO PO
add mapped point out_random_num[1] out_random_num[1] -type PO PO
add mapped point out_random_num[0] out_random_num[0] -type PO PO
add mapped point out_request_rand out_request_rand -type PO PO

//inout ports




//Sequential Pins
add mapped point snake_logic/counter[1]/q snake_logic_counter_reg[1]/QN -type DFF DFF
add mapped point snake_logic/counter[4]/q snake_logic_counter_reg[4]/QN -type DFF DFF
add mapped point snake_logic/to_controller[1]/q snake_logic_to_controller_reg[1]/QN -type DFF DFF
add mapped point snake_logic/led_array[6][5]/q snake_logic_led_array_reg[6][5]/QN -type DFF DFF
add mapped point snake_logic/led_array[7][5]/q snake_logic_led_array_reg[7][5]/QN -type DFF DFF
add mapped point snake_logic/counter[3]/q snake_logic_counter_reg[3]/QN -type DFF DFF
add mapped point snake_logic/led_array[6][7]/q snake_logic_led_array_reg[6][7]/QN -type DFF DFF
add mapped point snake_logic/led_array[4][0]/q snake_logic_led_array_reg[4][0]/QN -type DFF DFF
add mapped point snake_logic/led_array[6][1]/q snake_logic_led_array_reg[6][1]/QN -type DFF DFF
add mapped point snake_logic/led_array[7][1]/q snake_logic_led_array_reg[7][1]/QN -type DFF DFF
add mapped point snake_logic/led_array[5][3]/q snake_logic_led_array_reg[5][3]/QN -type DFF DFF
add mapped point snake_logic/led_array[1][0]/q snake_logic_led_array_reg[1][0]/QN -type DFF DFF
add mapped point snake_logic/led_array[4][4]/q snake_logic_led_array_reg[4][4]/QN -type DFF DFF
add mapped point snake_logic/led_array[1][2]/q snake_logic_led_array_reg[1][2]/QN -type DFF DFF
add mapped point snake_logic/led_array[1][1]/q snake_logic_led_array_reg[1][1]/QN -type DFF DFF
add mapped point snake_logic/counter[2]/q snake_logic_counter_reg[2]/QN -type DFF DFF
add mapped point snake_logic/counter[5]/q snake_logic_counter_reg[5]/QN -type DFF DFF
add mapped point snake_logic/counter[0]/q snake_logic_counter_reg[0]/Q -type DFF DFF
add mapped point snake_logic/led_array[5][6]/q snake_logic_led_array_reg[5][6]/QN -type DFF DFF
add mapped point snake_logic/led_array[4][2]/q snake_logic_led_array_reg[4][2]/QN -type DFF DFF
add mapped point snake_logic/led_array[2][7]/q snake_logic_led_array_reg[2][7]/QN -type DFF DFF
add mapped point snake_logic/led_array[2][6]/q snake_logic_led_array_reg[2][6]/QN -type DFF DFF
add mapped point snake_logic/led_array[3][4]/q snake_logic_led_array_reg[3][4]/QN -type DFF DFF
add mapped point snake_logic/led_array[3][5]/q snake_logic_led_array_reg[3][5]/QN -type DFF DFF
add mapped point snake_logic/led_array[2][5]/q snake_logic_led_array_reg[2][5]/QN -type DFF DFF
add mapped point snake_logic/led_array[7][7]/q snake_logic_led_array_reg[7][7]/QN -type DFF DFF
add mapped point snake_logic/led_array[2][4]/q snake_logic_led_array_reg[2][4]/QN -type DFF DFF
add mapped point snake_logic/led_array[2][3]/q snake_logic_led_array_reg[2][3]/QN -type DFF DFF
add mapped point snake_logic/led_array[2][1]/q snake_logic_led_array_reg[2][1]/QN -type DFF DFF
add mapped point snake_logic/led_array[2][2]/q snake_logic_led_array_reg[2][2]/QN -type DFF DFF
add mapped point snake_logic/led_array[3][0]/q snake_logic_led_array_reg[3][0]/QN -type DFF DFF
add mapped point snake_logic/led_array[3][1]/q snake_logic_led_array_reg[3][1]/QN -type DFF DFF
add mapped point snake_logic/led_array[2][0]/q snake_logic_led_array_reg[2][0]/QN -type DFF DFF
add mapped point snake_logic/request_rand/q snake_logic_request_rand_reg/QN -type DFF DFF
add mapped point snake_logic/led_array[4][5]/q snake_logic_led_array_reg[4][5]/QN -type DFF DFF
add mapped point snake_logic/led_array[1][5]/q snake_logic_led_array_reg[1][5]/QN -type DFF DFF
add mapped point snake_logic/led_array[1][7]/q snake_logic_led_array_reg[1][7]/QN -type DFF DFF
add mapped point snake_logic/snake_length[2]/q snake_logic_snake_length_reg[2]/QN -type DFF DFF
add mapped point snake_logic/led_array[4][7]/q snake_logic_led_array_reg[4][7]/QN -type DFF DFF
add mapped point snake_logic/led_array[1][6]/q snake_logic_led_array_reg[1][6]/QN -type DFF DFF
add mapped point snake_logic/led_array[1][4]/q snake_logic_led_array_reg[1][4]/QN -type DFF DFF
add mapped point snake_logic/led_array[0][6]/q snake_logic_led_array_reg[0][6]/QN -type DFF DFF
add mapped point snake_logic/led_array[0][4]/q snake_logic_led_array_reg[0][4]/QN -type DFF DFF
add mapped point snake_logic/led_array[0][5]/q snake_logic_led_array_reg[0][5]/QN -type DFF DFF
add mapped point snake_logic/led_array[3][2]/q snake_logic_led_array_reg[3][2]/QN -type DFF DFF
add mapped point snake_logic/led_array[3][3]/q snake_logic_led_array_reg[3][3]/QN -type DFF DFF
add mapped point snake_logic/led_array[7][6]/q snake_logic_led_array_reg[7][6]/QN -type DFF DFF
add mapped point snake_logic/led_array[3][6]/q snake_logic_led_array_reg[3][6]/QN -type DFF DFF
add mapped point snake_logic/snake_length[4]/q snake_logic_snake_length_reg[4]/QN -type DFF DFF
add mapped point snake_logic/snake_length[5]/q snake_logic_snake_length_reg[5]/QN -type DFF DFF
add mapped point snake_logic/snake_length[3]/q snake_logic_snake_length_reg[3]/QN -type DFF DFF
add mapped point snake_logic/led_array[3][7]/q snake_logic_led_array_reg[3][7]/QN -type DFF DFF
add mapped point snake_logic/snake_length[1]/q snake_logic_snake_length_reg[1]/QN -type DFF DFF
add mapped point snake_logic/led_array[5][4]/q snake_logic_led_array_reg[5][4]/QN -type DFF DFF
add mapped point snake_logic/led_array[7][4]/q snake_logic_led_array_reg[7][4]/QN -type DFF DFF
add mapped point snake_logic/led_array[0][7]/q snake_logic_led_array_reg[0][7]/QN -type DFF DFF
add mapped point snake_logic/led_array[4][1]/q snake_logic_led_array_reg[4][1]/QN -type DFF DFF
add mapped point snake_logic/led_array[6][4]/q snake_logic_led_array_reg[6][4]/QN -type DFF DFF
add mapped point snake_logic/led_array[5][5]/q snake_logic_led_array_reg[5][5]/QN -type DFF DFF
add mapped point snake_logic/led_array[0][1]/q snake_logic_led_array_reg[0][1]/QN -type DFF DFF
add mapped point snake_logic/led_array[4][6]/q snake_logic_led_array_reg[4][6]/QN -type DFF DFF
add mapped point snake_logic/led_array[6][0]/q snake_logic_led_array_reg[6][0]/QN -type DFF DFF
add mapped point snake_logic/led_array[7][0]/q snake_logic_led_array_reg[7][0]/QN -type DFF DFF
add mapped point snake_logic/led_array[0][3]/q snake_logic_led_array_reg[0][3]/QN -type DFF DFF
add mapped point snake_logic/led_array[5][0]/q snake_logic_led_array_reg[5][0]/QN -type DFF DFF
add mapped point snake_logic/led_array[5][1]/q snake_logic_led_array_reg[5][1]/QN -type DFF DFF
add mapped point snake_logic/led_array[0][0]/q snake_logic_led_array_reg[0][0]/QN -type DFF DFF
add mapped point snake_logic/led_array[0][2]/q snake_logic_led_array_reg[0][2]/QN -type DFF DFF
add mapped point snake_logic/led_array[1][3]/q snake_logic_led_array_reg[1][3]/QN -type DFF DFF
add mapped point snake_logic/led_array[6][2]/q snake_logic_led_array_reg[6][2]/QN -type DFF DFF
add mapped point snake_logic/led_array[7][2]/q snake_logic_led_array_reg[7][2]/QN -type DFF DFF
add mapped point snake_logic/led_array[7][3]/q snake_logic_led_array_reg[7][3]/QN -type DFF DFF
add mapped point snake_logic/led_array[6][3]/q snake_logic_led_array_reg[6][3]/QN -type DFF DFF
add mapped point snake_logic/led_array[4][3]/q snake_logic_led_array_reg[4][3]/QN -type DFF DFF
add mapped point snake_logic/led_array[5][2]/q snake_logic_led_array_reg[5][2]/QN -type DFF DFF
add mapped point snake_logic/led_array[5][7]/q snake_logic_led_array_reg[5][7]/QN -type DFF DFF
add mapped point snake_logic/led_array[6][6]/q snake_logic_led_array_reg[6][6]/QN -type DFF DFF
add mapped point snake_logic/snake_length[0]/q snake_logic_snake_length_reg[0]/QN -type DFF DFF
add mapped point snake_logic/snake_body[13][3]/q snake_logic_snake_body_reg[13][3]/QN -type DFF DFF
add mapped point snake_logic/snake_body[13][0]/q snake_logic_snake_body_reg[13][0]/QN -type DFF DFF
add mapped point snake_logic/snake_body[13][1]/q snake_logic_snake_body_reg[13][1]/QN -type DFF DFF
add mapped point snake_logic/snake_body[13][2]/q snake_logic_snake_body_reg[13][2]/QN -type DFF DFF
add mapped point snake_logic/snake_body[9][0]/q snake_logic_snake_body_reg[9][0]/QN -type DFF DFF
add mapped point snake_logic/snake_body[9][1]/q snake_logic_snake_body_reg[9][1]/QN -type DFF DFF
add mapped point snake_logic/snake_body[9][2]/q snake_logic_snake_body_reg[9][2]/QN -type DFF DFF
add mapped point snake_logic/snake_body[9][3]/q snake_logic_snake_body_reg[9][3]/QN -type DFF DFF
add mapped point snake_logic/snake_body[9][4]/q snake_logic_snake_body_reg[9][4]/QN -type DFF DFF
add mapped point snake_logic/snake_body[9][5]/q snake_logic_snake_body_reg[9][5]/QN -type DFF DFF
add mapped point snake_logic/snake_body[27][5]/q snake_logic_snake_body_reg[27][5]/QN -type DFF DFF
add mapped point snake_logic/snake_body[29][0]/q snake_logic_snake_body_reg[29][0]/QN -type DFF DFF
add mapped point snake_logic/snake_body[29][1]/q snake_logic_snake_body_reg[29][1]/QN -type DFF DFF
add mapped point snake_logic/snake_body[29][2]/q snake_logic_snake_body_reg[29][2]/QN -type DFF DFF
add mapped point snake_logic/snake_body[29][3]/q snake_logic_snake_body_reg[29][3]/QN -type DFF DFF
add mapped point snake_logic/snake_body[29][4]/q snake_logic_snake_body_reg[29][4]/QN -type DFF DFF
add mapped point snake_logic/snake_body[29][5]/q snake_logic_snake_body_reg[29][5]/QN -type DFF DFF
add mapped point snake_logic/snake_body[31][1]/q snake_logic_snake_body_reg[31][1]/QN -type DFF DFF
add mapped point snake_logic/snake_body[25][0]/q snake_logic_snake_body_reg[25][0]/QN -type DFF DFF
add mapped point snake_logic/snake_body[25][1]/q snake_logic_snake_body_reg[25][1]/QN -type DFF DFF
add mapped point snake_logic/snake_body[25][2]/q snake_logic_snake_body_reg[25][2]/QN -type DFF DFF
add mapped point snake_logic/snake_body[25][3]/q snake_logic_snake_body_reg[25][3]/QN -type DFF DFF
add mapped point snake_logic/snake_body[25][4]/q snake_logic_snake_body_reg[25][4]/QN -type DFF DFF
add mapped point snake_logic/snake_body[27][0]/q snake_logic_snake_body_reg[27][0]/QN -type DFF DFF
add mapped point snake_logic/snake_body[27][1]/q snake_logic_snake_body_reg[27][1]/QN -type DFF DFF
add mapped point snake_logic/snake_body[27][2]/q snake_logic_snake_body_reg[27][2]/QN -type DFF DFF
add mapped point snake_logic/snake_body[27][4]/q snake_logic_snake_body_reg[27][4]/QN -type DFF DFF
add mapped point snake_logic/snake_body[31][0]/q snake_logic_snake_body_reg[31][0]/QN -type DFF DFF
add mapped point snake_logic/snake_body[27][3]/q snake_logic_snake_body_reg[27][3]/QN -type DFF DFF
add mapped point snake_logic/snake_body[31][2]/q snake_logic_snake_body_reg[31][2]/QN -type DFF DFF
add mapped point snake_logic/snake_body[25][5]/q snake_logic_snake_body_reg[25][5]/QN -type DFF DFF
add mapped point snake_logic/snake_body[31][3]/q snake_logic_snake_body_reg[31][3]/QN -type DFF DFF
add mapped point snake_logic/snake_body[31][4]/q snake_logic_snake_body_reg[31][4]/QN -type DFF DFF
add mapped point snake_logic/snake_body[31][5]/q snake_logic_snake_body_reg[31][5]/QN -type DFF DFF
add mapped point snake_logic/snake_body[3][5]/q snake_logic_snake_body_reg[3][5]/QN -type DFF DFF
add mapped point snake_logic/snake_body[41][3]/q snake_logic_snake_body_reg[41][3]/QN -type DFF DFF
add mapped point snake_logic/snake_body[43][5]/q snake_logic_snake_body_reg[43][5]/QN -type DFF DFF
add mapped point snake_logic/snake_body[41][5]/q snake_logic_snake_body_reg[41][5]/QN -type DFF DFF
add mapped point snake_logic/snake_body[47][5]/q snake_logic_snake_body_reg[47][5]/QN -type DFF DFF
add mapped point snake_logic/snake_body[43][1]/q snake_logic_snake_body_reg[43][1]/QN -type DFF DFF
add mapped point snake_logic/snake_body[57][5]/q snake_logic_snake_body_reg[57][5]/QN -type DFF DFF
add mapped point snake_logic/snake_body[35][0]/q snake_logic_snake_body_reg[35][0]/QN -type DFF DFF
add mapped point snake_logic/snake_body[35][2]/q snake_logic_snake_body_reg[35][2]/QN -type DFF DFF
add mapped point snake_logic/snake_body[61][4]/q snake_logic_snake_body_reg[61][4]/QN -type DFF DFF
add mapped point snake_logic/snake_body[35][3]/q snake_logic_snake_body_reg[35][3]/QN -type DFF DFF
add mapped point snake_logic/snake_body[57][0]/q snake_logic_snake_body_reg[57][0]/QN -type DFF DFF
add mapped point snake_logic/snake_body[57][1]/q snake_logic_snake_body_reg[57][1]/QN -type DFF DFF
add mapped point snake_logic/snake_body[57][2]/q snake_logic_snake_body_reg[57][2]/QN -type DFF DFF
add mapped point snake_logic/snake_body[57][3]/q snake_logic_snake_body_reg[57][3]/QN -type DFF DFF
add mapped point snake_logic/snake_body[57][4]/q snake_logic_snake_body_reg[57][4]/QN -type DFF DFF
add mapped point snake_logic/snake_body[3][0]/q snake_logic_snake_body_reg[3][0]/QN -type DFF DFF
add mapped point snake_logic/snake_body[3][1]/q snake_logic_snake_body_reg[3][1]/QN -type DFF DFF
add mapped point snake_logic/snake_body[3][2]/q snake_logic_snake_body_reg[3][2]/QN -type DFF DFF
add mapped point snake_logic/snake_body[3][3]/q snake_logic_snake_body_reg[3][3]/QN -type DFF DFF
add mapped point snake_logic/snake_body[3][4]/q snake_logic_snake_body_reg[3][4]/QN -type DFF DFF
add mapped point snake_logic/snake_body[7][0]/q snake_logic_snake_body_reg[7][0]/QN -type DFF DFF
add mapped point snake_logic/snake_body[7][1]/q snake_logic_snake_body_reg[7][1]/QN -type DFF DFF
add mapped point snake_logic/snake_body[7][2]/q snake_logic_snake_body_reg[7][2]/QN -type DFF DFF
add mapped point snake_logic/snake_body[7][4]/q snake_logic_snake_body_reg[7][4]/QN -type DFF DFF
add mapped point snake_logic/snake_body[7][5]/q snake_logic_snake_body_reg[7][5]/QN -type DFF DFF
add mapped point snake_logic/snake_body[47][1]/q snake_logic_snake_body_reg[47][1]/QN -type DFF DFF
add mapped point snake_logic/snake_body[33][0]/q snake_logic_snake_body_reg[33][0]/QN -type DFF DFF
add mapped point snake_logic/snake_body[33][1]/q snake_logic_snake_body_reg[33][1]/QN -type DFF DFF
add mapped point snake_logic/snake_body[33][3]/q snake_logic_snake_body_reg[33][3]/QN -type DFF DFF
add mapped point snake_logic/snake_body[33][4]/q snake_logic_snake_body_reg[33][4]/QN -type DFF DFF
add mapped point snake_logic/snake_body[33][5]/q snake_logic_snake_body_reg[33][5]/QN -type DFF DFF
add mapped point snake_logic/snake_body[39][0]/q snake_logic_snake_body_reg[39][0]/QN -type DFF DFF
add mapped point snake_logic/snake_body[39][1]/q snake_logic_snake_body_reg[39][1]/QN -type DFF DFF
add mapped point snake_logic/snake_body[39][2]/q snake_logic_snake_body_reg[39][2]/QN -type DFF DFF
add mapped point snake_logic/snake_body[39][3]/q snake_logic_snake_body_reg[39][3]/QN -type DFF DFF
add mapped point snake_logic/snake_body[39][4]/q snake_logic_snake_body_reg[39][4]/QN -type DFF DFF
add mapped point snake_logic/snake_body[39][5]/q snake_logic_snake_body_reg[39][5]/QN -type DFF DFF
add mapped point snake_logic/snake_body[41][0]/q snake_logic_snake_body_reg[41][0]/QN -type DFF DFF
add mapped point snake_logic/snake_body[41][1]/q snake_logic_snake_body_reg[41][1]/QN -type DFF DFF
add mapped point snake_logic/snake_body[41][2]/q snake_logic_snake_body_reg[41][2]/QN -type DFF DFF
add mapped point snake_logic/snake_body[41][4]/q snake_logic_snake_body_reg[41][4]/QN -type DFF DFF
add mapped point snake_logic/snake_body[7][3]/q snake_logic_snake_body_reg[7][3]/QN -type DFF DFF
add mapped point snake_logic/snake_body[43][0]/q snake_logic_snake_body_reg[43][0]/QN -type DFF DFF
add mapped point snake_logic/snake_body[61][5]/q snake_logic_snake_body_reg[61][5]/QN -type DFF DFF
add mapped point snake_logic/snake_body[33][2]/q snake_logic_snake_body_reg[33][2]/QN -type DFF DFF
add mapped point snake_logic/snake_body[14][1]/q snake_logic_snake_body_reg[14][1]/QN -type DFF DFF
add mapped point snake_logic/snake_body[14][0]/q snake_logic_snake_body_reg[14][0]/QN -type DFF DFF
add mapped point snake_logic/snake_body[10][1]/q snake_logic_snake_body_reg[10][1]/QN -type DFF DFF
add mapped point snake_logic/snake_body[10][0]/q snake_logic_snake_body_reg[10][0]/QN -type DFF DFF
add mapped point snake_logic/snake_body[47][4]/q snake_logic_snake_body_reg[47][4]/QN -type DFF DFF
add mapped point snake_logic/snake_body[47][3]/q snake_logic_snake_body_reg[47][3]/QN -type DFF DFF
add mapped point snake_logic/snake_body[47][2]/q snake_logic_snake_body_reg[47][2]/QN -type DFF DFF
add mapped point snake_logic/snake_body[47][0]/q snake_logic_snake_body_reg[47][0]/QN -type DFF DFF
add mapped point snake_logic/snake_body[45][5]/q snake_logic_snake_body_reg[45][5]/QN -type DFF DFF
add mapped point snake_logic/snake_body[45][4]/q snake_logic_snake_body_reg[45][4]/QN -type DFF DFF
add mapped point snake_logic/snake_body[45][3]/q snake_logic_snake_body_reg[45][3]/QN -type DFF DFF
add mapped point snake_logic/snake_body[45][2]/q snake_logic_snake_body_reg[45][2]/QN -type DFF DFF
add mapped point snake_logic/snake_body[45][1]/q snake_logic_snake_body_reg[45][1]/QN -type DFF DFF
add mapped point snake_logic/snake_body[45][0]/q snake_logic_snake_body_reg[45][0]/QN -type DFF DFF
add mapped point snake_logic/snake_body[43][4]/q snake_logic_snake_body_reg[43][4]/QN -type DFF DFF
add mapped point snake_logic/snake_body[43][3]/q snake_logic_snake_body_reg[43][3]/QN -type DFF DFF
add mapped point snake_logic/snake_body[43][2]/q snake_logic_snake_body_reg[43][2]/QN -type DFF DFF
add mapped point snake_logic/snake_body[21][2]/q snake_logic_snake_body_reg[21][2]/QN -type DFF DFF
add mapped point snake_logic/snake_body[8][5]/q snake_logic_snake_body_reg[8][5]/QN -type DFF DFF
add mapped point snake_logic/snake_body[30][4]/q snake_logic_snake_body_reg[30][4]/QN -type DFF DFF
add mapped point snake_logic/snake_body[30][5]/q snake_logic_snake_body_reg[30][5]/QN -type DFF DFF
add mapped point snake_logic/snake_body[11][3]/q snake_logic_snake_body_reg[11][3]/QN -type DFF DFF
add mapped point snake_logic/snake_body[11][4]/q snake_logic_snake_body_reg[11][4]/QN -type DFF DFF
add mapped point snake_logic/snake_body[11][5]/q snake_logic_snake_body_reg[11][5]/QN -type DFF DFF
add mapped point snake_logic/snake_body[13][4]/q snake_logic_snake_body_reg[13][4]/QN -type DFF DFF
add mapped point snake_logic/snake_body[13][5]/q snake_logic_snake_body_reg[13][5]/QN -type DFF DFF
add mapped point snake_logic/snake_body[17][0]/q snake_logic_snake_body_reg[17][0]/QN -type DFF DFF
add mapped point snake_logic/snake_body[17][1]/q snake_logic_snake_body_reg[17][1]/QN -type DFF DFF
add mapped point snake_logic/snake_body[17][2]/q snake_logic_snake_body_reg[17][2]/QN -type DFF DFF
add mapped point snake_logic/snake_body[17][3]/q snake_logic_snake_body_reg[17][3]/QN -type DFF DFF
add mapped point snake_logic/snake_body[17][4]/q snake_logic_snake_body_reg[17][4]/QN -type DFF DFF
add mapped point snake_logic/snake_body[19][0]/q snake_logic_snake_body_reg[19][0]/QN -type DFF DFF
add mapped point snake_logic/snake_body[19][1]/q snake_logic_snake_body_reg[19][1]/QN -type DFF DFF
add mapped point snake_logic/snake_body[19][2]/q snake_logic_snake_body_reg[19][2]/QN -type DFF DFF
add mapped point snake_logic/snake_body[19][4]/q snake_logic_snake_body_reg[19][4]/QN -type DFF DFF
add mapped point snake_logic/snake_body[19][5]/q snake_logic_snake_body_reg[19][5]/QN -type DFF DFF
add mapped point snake_logic/snake_body[21][0]/q snake_logic_snake_body_reg[21][0]/QN -type DFF DFF
add mapped point snake_logic/snake_body[15][1]/q snake_logic_snake_body_reg[15][1]/QN -type DFF DFF
add mapped point snake_logic/snake_body[21][3]/q snake_logic_snake_body_reg[21][3]/QN -type DFF DFF
add mapped point snake_logic/snake_body[21][4]/q snake_logic_snake_body_reg[21][4]/QN -type DFF DFF
add mapped point snake_logic/snake_body[11][0]/q snake_logic_snake_body_reg[11][0]/QN -type DFF DFF
add mapped point snake_logic/snake_body[15][0]/q snake_logic_snake_body_reg[15][0]/QN -type DFF DFF
add mapped point snake_logic/snake_body[11][1]/q snake_logic_snake_body_reg[11][1]/QN -type DFF DFF
add mapped point snake_logic/snake_body[8][0]/q snake_logic_snake_body_reg[8][0]/QN -type DFF DFF
add mapped point snake_logic/snake_body[8][1]/q snake_logic_snake_body_reg[8][1]/QN -type DFF DFF
add mapped point snake_logic/snake_body[8][4]/q snake_logic_snake_body_reg[8][4]/QN -type DFF DFF
add mapped point snake_logic/snake_body[8][3]/q snake_logic_snake_body_reg[8][3]/QN -type DFF DFF
add mapped point snake_logic/snake_body[24][0]/q snake_logic_snake_body_reg[24][0]/QN -type DFF DFF
add mapped point snake_logic/snake_body[24][1]/q snake_logic_snake_body_reg[24][1]/QN -type DFF DFF
add mapped point snake_logic/snake_body[24][3]/q snake_logic_snake_body_reg[24][3]/QN -type DFF DFF
add mapped point snake_logic/snake_body[24][4]/q snake_logic_snake_body_reg[24][4]/QN -type DFF DFF
add mapped point snake_logic/snake_body[24][5]/q snake_logic_snake_body_reg[24][5]/QN -type DFF DFF
add mapped point snake_logic/snake_body[24][2]/q snake_logic_snake_body_reg[24][2]/QN -type DFF DFF
add mapped point snake_logic/snake_body[26][1]/q snake_logic_snake_body_reg[26][1]/QN -type DFF DFF
add mapped point snake_logic/snake_body[26][2]/q snake_logic_snake_body_reg[26][2]/QN -type DFF DFF
add mapped point snake_logic/snake_body[26][3]/q snake_logic_snake_body_reg[26][3]/QN -type DFF DFF
add mapped point snake_logic/snake_body[26][5]/q snake_logic_snake_body_reg[26][5]/QN -type DFF DFF
add mapped point snake_logic/snake_body[28][0]/q snake_logic_snake_body_reg[28][0]/QN -type DFF DFF
add mapped point snake_logic/snake_body[28][1]/q snake_logic_snake_body_reg[28][1]/QN -type DFF DFF
add mapped point snake_logic/snake_body[28][3]/q snake_logic_snake_body_reg[28][3]/QN -type DFF DFF
add mapped point snake_logic/snake_body[28][4]/q snake_logic_snake_body_reg[28][4]/QN -type DFF DFF
add mapped point snake_logic/snake_body[28][5]/q snake_logic_snake_body_reg[28][5]/QN -type DFF DFF
add mapped point snake_logic/snake_body[30][1]/q snake_logic_snake_body_reg[30][1]/QN -type DFF DFF
add mapped point snake_logic/snake_body[30][2]/q snake_logic_snake_body_reg[30][2]/QN -type DFF DFF
add mapped point snake_logic/snake_body[30][3]/q snake_logic_snake_body_reg[30][3]/QN -type DFF DFF
add mapped point snake_logic/snake_body[11][2]/q snake_logic_snake_body_reg[11][2]/QN -type DFF DFF
add mapped point snake_logic/snake_body[19][3]/q snake_logic_snake_body_reg[19][3]/QN -type DFF DFF
add mapped point snake_logic/snake_body[21][1]/q snake_logic_snake_body_reg[21][1]/QN -type DFF DFF
add mapped point snake_logic/snake_body[21][5]/q snake_logic_snake_body_reg[21][5]/QN -type DFF DFF
add mapped point snake_logic/snake_body[17][5]/q snake_logic_snake_body_reg[17][5]/QN -type DFF DFF
add mapped point snake_logic/snake_body[26][4]/q snake_logic_snake_body_reg[26][4]/QN -type DFF DFF
add mapped point snake_logic/snake_body[26][0]/q snake_logic_snake_body_reg[26][0]/QN -type DFF DFF
add mapped point snake_logic/snake_body[28][2]/q snake_logic_snake_body_reg[28][2]/QN -type DFF DFF
add mapped point snake_logic/snake_body[30][0]/q snake_logic_snake_body_reg[30][0]/QN -type DFF DFF
add mapped point snake_logic/snake_body[8][2]/q snake_logic_snake_body_reg[8][2]/QN -type DFF DFF
add mapped point snake_logic/snake_body[37][4]/q snake_logic_snake_body_reg[37][4]/QN -type DFF DFF
add mapped point snake_logic/snake_body[61][2]/q snake_logic_snake_body_reg[61][2]/QN -type DFF DFF
add mapped point snake_logic/snake_body[61][1]/q snake_logic_snake_body_reg[61][1]/QN -type DFF DFF
add mapped point snake_logic/snake_body[59][3]/q snake_logic_snake_body_reg[59][3]/QN -type DFF DFF
add mapped point snake_logic/snake_body[32][2]/q snake_logic_snake_body_reg[32][2]/QN -type DFF DFF
add mapped point snake_logic/snake_body[14][4]/q snake_logic_snake_body_reg[14][4]/QN -type DFF DFF
add mapped point snake_logic/snake_body[56][4]/q snake_logic_snake_body_reg[56][4]/QN -type DFF DFF
add mapped point snake_logic/snake_body[12][2]/q snake_logic_snake_body_reg[12][2]/QN -type DFF DFF
add mapped point snake_logic/snake_body[10][3]/q snake_logic_snake_body_reg[10][3]/QN -type DFF DFF
add mapped point snake_logic/snake_body[12][3]/q snake_logic_snake_body_reg[12][3]/QN -type DFF DFF
add mapped point snake_logic/snake_body[49][0]/q snake_logic_snake_body_reg[49][0]/QN -type DFF DFF
add mapped point snake_logic/snake_body[49][1]/q snake_logic_snake_body_reg[49][1]/QN -type DFF DFF
add mapped point snake_logic/snake_body[49][2]/q snake_logic_snake_body_reg[49][2]/QN -type DFF DFF
add mapped point snake_logic/snake_body[49][3]/q snake_logic_snake_body_reg[49][3]/QN -type DFF DFF
add mapped point snake_logic/snake_body[49][4]/q snake_logic_snake_body_reg[49][4]/QN -type DFF DFF
add mapped point snake_logic/snake_body[49][5]/q snake_logic_snake_body_reg[49][5]/QN -type DFF DFF
add mapped point snake_logic/snake_body[51][0]/q snake_logic_snake_body_reg[51][0]/QN -type DFF DFF
add mapped point snake_logic/snake_body[51][1]/q snake_logic_snake_body_reg[51][1]/QN -type DFF DFF
add mapped point snake_logic/snake_body[51][2]/q snake_logic_snake_body_reg[51][2]/QN -type DFF DFF
add mapped point snake_logic/snake_body[51][4]/q snake_logic_snake_body_reg[51][4]/QN -type DFF DFF
add mapped point snake_logic/snake_body[51][5]/q snake_logic_snake_body_reg[51][5]/QN -type DFF DFF
add mapped point snake_logic/snake_body[53][0]/q snake_logic_snake_body_reg[53][0]/QN -type DFF DFF
add mapped point snake_logic/snake_body[53][2]/q snake_logic_snake_body_reg[53][2]/QN -type DFF DFF
add mapped point snake_logic/snake_body[53][3]/q snake_logic_snake_body_reg[53][3]/QN -type DFF DFF
add mapped point snake_logic/snake_body[53][4]/q snake_logic_snake_body_reg[53][4]/QN -type DFF DFF
add mapped point snake_logic/snake_body[55][1]/q snake_logic_snake_body_reg[55][1]/QN -type DFF DFF
add mapped point snake_logic/snake_body[55][2]/q snake_logic_snake_body_reg[55][2]/QN -type DFF DFF
add mapped point snake_logic/snake_body[55][3]/q snake_logic_snake_body_reg[55][3]/QN -type DFF DFF
add mapped point snake_logic/snake_body[55][5]/q snake_logic_snake_body_reg[55][5]/QN -type DFF DFF
add mapped point snake_logic/snake_body[55][0]/q snake_logic_snake_body_reg[55][0]/QN -type DFF DFF
add mapped point snake_logic/snake_body[59][0]/q snake_logic_snake_body_reg[59][0]/QN -type DFF DFF
add mapped point snake_logic/snake_body[59][1]/q snake_logic_snake_body_reg[59][1]/QN -type DFF DFF
add mapped point snake_logic/snake_body[59][2]/q snake_logic_snake_body_reg[59][2]/QN -type DFF DFF
add mapped point snake_logic/snake_body[59][5]/q snake_logic_snake_body_reg[59][5]/QN -type DFF DFF
add mapped point snake_logic/snake_body[61][0]/q snake_logic_snake_body_reg[61][0]/QN -type DFF DFF
add mapped point snake_logic/snake_body[61][3]/q snake_logic_snake_body_reg[61][3]/QN -type DFF DFF
add mapped point snake_logic/snake_body[59][4]/q snake_logic_snake_body_reg[59][4]/QN -type DFF DFF
add mapped point snake_logic/snake_body[15][2]/q snake_logic_snake_body_reg[15][2]/QN -type DFF DFF
add mapped point snake_logic/snake_body[15][4]/q snake_logic_snake_body_reg[15][4]/QN -type DFF DFF
add mapped point snake_logic/snake_body[15][5]/q snake_logic_snake_body_reg[15][5]/QN -type DFF DFF
add mapped point snake_logic/snake_body[35][5]/q snake_logic_snake_body_reg[35][5]/QN -type DFF DFF
add mapped point snake_logic/snake_body[40][4]/q snake_logic_snake_body_reg[40][4]/QN -type DFF DFF
add mapped point snake_logic/snake_body[56][0]/q snake_logic_snake_body_reg[56][0]/QN -type DFF DFF
add mapped point snake_logic/snake_body[56][1]/q snake_logic_snake_body_reg[56][1]/QN -type DFF DFF
add mapped point snake_logic/snake_body[56][2]/q snake_logic_snake_body_reg[56][2]/QN -type DFF DFF
add mapped point snake_logic/snake_body[56][3]/q snake_logic_snake_body_reg[56][3]/QN -type DFF DFF
add mapped point snake_logic/snake_body[56][5]/q snake_logic_snake_body_reg[56][5]/QN -type DFF DFF
add mapped point snake_logic/snake_body[1][2]/q snake_logic_snake_body_reg[1][2]/QN -type DFF DFF
add mapped point snake_logic/snake_body[1][3]/q snake_logic_snake_body_reg[1][3]/QN -type DFF DFF
add mapped point snake_logic/snake_body[1][4]/q snake_logic_snake_body_reg[1][4]/QN -type DFF DFF
add mapped point snake_logic/snake_body[1][5]/q snake_logic_snake_body_reg[1][5]/QN -type DFF DFF
add mapped point snake_logic/snake_body[1][0]/q snake_logic_snake_body_reg[1][0]/QN -type DFF DFF
add mapped point snake_logic/snake_body[1][1]/q snake_logic_snake_body_reg[1][1]/QN -type DFF DFF
add mapped point snake_logic/snake_body[5][0]/q snake_logic_snake_body_reg[5][0]/QN -type DFF DFF
add mapped point snake_logic/snake_body[5][1]/q snake_logic_snake_body_reg[5][1]/QN -type DFF DFF
add mapped point snake_logic/snake_body[5][4]/q snake_logic_snake_body_reg[5][4]/QN -type DFF DFF
add mapped point snake_logic/snake_body[5][5]/q snake_logic_snake_body_reg[5][5]/QN -type DFF DFF
add mapped point snake_logic/snake_body[6][0]/q snake_logic_snake_body_reg[6][0]/QN -type DFF DFF
add mapped point snake_logic/snake_body[6][1]/q snake_logic_snake_body_reg[6][1]/QN -type DFF DFF
add mapped point snake_logic/snake_body[6][3]/q snake_logic_snake_body_reg[6][3]/QN -type DFF DFF
add mapped point snake_logic/snake_body[6][4]/q snake_logic_snake_body_reg[6][4]/QN -type DFF DFF
add mapped point snake_logic/snake_body[6][5]/q snake_logic_snake_body_reg[6][5]/QN -type DFF DFF
add mapped point snake_logic/snake_body[5][3]/q snake_logic_snake_body_reg[5][3]/QN -type DFF DFF
add mapped point snake_logic/snake_body[10][2]/q snake_logic_snake_body_reg[10][2]/QN -type DFF DFF
add mapped point snake_logic/snake_body[10][4]/q snake_logic_snake_body_reg[10][4]/QN -type DFF DFF
add mapped point snake_logic/snake_body[10][5]/q snake_logic_snake_body_reg[10][5]/QN -type DFF DFF
add mapped point snake_logic/snake_body[12][0]/q snake_logic_snake_body_reg[12][0]/QN -type DFF DFF
add mapped point snake_logic/snake_body[12][1]/q snake_logic_snake_body_reg[12][1]/QN -type DFF DFF
add mapped point snake_logic/snake_body[12][5]/q snake_logic_snake_body_reg[12][5]/QN -type DFF DFF
add mapped point snake_logic/snake_body[12][4]/q snake_logic_snake_body_reg[12][4]/QN -type DFF DFF
add mapped point snake_logic/snake_body[14][2]/q snake_logic_snake_body_reg[14][2]/QN -type DFF DFF
add mapped point snake_logic/snake_body[14][3]/q snake_logic_snake_body_reg[14][3]/QN -type DFF DFF
add mapped point snake_logic/snake_body[14][5]/q snake_logic_snake_body_reg[14][5]/QN -type DFF DFF
add mapped point snake_logic/snake_body[51][3]/q snake_logic_snake_body_reg[51][3]/QN -type DFF DFF
add mapped point snake_logic/snake_body[5][2]/q snake_logic_snake_body_reg[5][2]/QN -type DFF DFF
add mapped point snake_logic/snake_body[55][4]/q snake_logic_snake_body_reg[55][4]/QN -type DFF DFF
add mapped point snake_logic/snake_body[37][2]/q snake_logic_snake_body_reg[37][2]/QN -type DFF DFF
add mapped point snake_logic/snake_body[37][3]/q snake_logic_snake_body_reg[37][3]/QN -type DFF DFF
add mapped point snake_logic/snake_body[37][5]/q snake_logic_snake_body_reg[37][5]/QN -type DFF DFF
add mapped point snake_logic/snake_body[40][0]/q snake_logic_snake_body_reg[40][0]/QN -type DFF DFF
add mapped point snake_logic/snake_body[35][4]/q snake_logic_snake_body_reg[35][4]/QN -type DFF DFF
add mapped point snake_logic/snake_body[40][1]/q snake_logic_snake_body_reg[40][1]/QN -type DFF DFF
add mapped point snake_logic/snake_body[40][2]/q snake_logic_snake_body_reg[40][2]/QN -type DFF DFF
add mapped point snake_logic/snake_body[40][3]/q snake_logic_snake_body_reg[40][3]/QN -type DFF DFF
add mapped point snake_logic/snake_body[40][5]/q snake_logic_snake_body_reg[40][5]/QN -type DFF DFF
add mapped point snake_logic/snake_body[53][5]/q snake_logic_snake_body_reg[53][5]/QN -type DFF DFF
add mapped point snake_logic/snake_body[6][2]/q snake_logic_snake_body_reg[6][2]/QN -type DFF DFF
add mapped point snake_logic/snake_body[53][1]/q snake_logic_snake_body_reg[53][1]/QN -type DFF DFF
add mapped point snake_logic/snake_body[32][0]/q snake_logic_snake_body_reg[32][0]/QN -type DFF DFF
add mapped point snake_logic/snake_body[15][3]/q snake_logic_snake_body_reg[15][3]/QN -type DFF DFF
add mapped point snake_logic/snake_body[32][1]/q snake_logic_snake_body_reg[32][1]/QN -type DFF DFF
add mapped point snake_logic/snake_body[32][3]/q snake_logic_snake_body_reg[32][3]/QN -type DFF DFF
add mapped point snake_logic/snake_body[32][4]/q snake_logic_snake_body_reg[32][4]/QN -type DFF DFF
add mapped point snake_logic/snake_body[32][5]/q snake_logic_snake_body_reg[32][5]/QN -type DFF DFF
add mapped point snake_logic/snake_body[35][1]/q snake_logic_snake_body_reg[35][1]/QN -type DFF DFF
add mapped point snake_logic/snake_body[37][0]/q snake_logic_snake_body_reg[37][0]/QN -type DFF DFF
add mapped point snake_logic/snake_body[37][1]/q snake_logic_snake_body_reg[37][1]/QN -type DFF DFF
add mapped point snake_logic/snake_body[4][2]/q snake_logic_snake_body_reg[4][2]/QN -type DFF DFF
add mapped point snake_logic/snake_body[18][0]/q snake_logic_snake_body_reg[18][0]/QN -type DFF DFF
add mapped point snake_logic/snake_body[23][0]/q snake_logic_snake_body_reg[23][0]/QN -type DFF DFF
add mapped point snake_logic/snake_body[23][1]/q snake_logic_snake_body_reg[23][1]/QN -type DFF DFF
add mapped point snake_logic/snake_body[23][2]/q snake_logic_snake_body_reg[23][2]/QN -type DFF DFF
add mapped point snake_logic/snake_body[23][5]/q snake_logic_snake_body_reg[23][5]/QN -type DFF DFF
add mapped point snake_logic/snake_body[18][5]/q snake_logic_snake_body_reg[18][5]/QN -type DFF DFF
add mapped point snake_logic/snake_body[58][5]/q snake_logic_snake_body_reg[58][5]/QN -type DFF DFF
add mapped point snake_logic/snake_body[4][4]/q snake_logic_snake_body_reg[4][4]/QN -type DFF DFF
add mapped point snake_logic/snake_body[2][2]/q snake_logic_snake_body_reg[2][2]/QN -type DFF DFF
add mapped point snake_logic/snake_body[2][3]/q snake_logic_snake_body_reg[2][3]/QN -type DFF DFF
add mapped point snake_logic/snake_body[20][2]/q snake_logic_snake_body_reg[20][2]/QN -type DFF DFF
add mapped point snake_logic/snake_body[2][5]/q snake_logic_snake_body_reg[2][5]/QN -type DFF DFF
add mapped point snake_logic/snake_body[2][1]/q snake_logic_snake_body_reg[2][1]/QN -type DFF DFF
add mapped point snake_logic/snake_body[16][3]/q snake_logic_snake_body_reg[16][3]/QN -type DFF DFF
add mapped point snake_logic/snake_body[4][3]/q snake_logic_snake_body_reg[4][3]/QN -type DFF DFF
add mapped point snake_logic/snake_body[4][5]/q snake_logic_snake_body_reg[4][5]/QN -type DFF DFF
add mapped point snake_logic/snake_body[16][1]/q snake_logic_snake_body_reg[16][1]/QN -type DFF DFF
add mapped point snake_logic/snake_body[16][2]/q snake_logic_snake_body_reg[16][2]/QN -type DFF DFF
add mapped point snake_logic/snake_body[16][0]/q snake_logic_snake_body_reg[16][0]/QN -type DFF DFF
add mapped point snake_logic/snake_body[16][5]/q snake_logic_snake_body_reg[16][5]/QN -type DFF DFF
add mapped point snake_logic/snake_body[16][4]/q snake_logic_snake_body_reg[16][4]/QN -type DFF DFF
add mapped point snake_logic/snake_body[18][1]/q snake_logic_snake_body_reg[18][1]/QN -type DFF DFF
add mapped point snake_logic/snake_body[18][3]/q snake_logic_snake_body_reg[18][3]/QN -type DFF DFF
add mapped point snake_logic/snake_body[18][4]/q snake_logic_snake_body_reg[18][4]/QN -type DFF DFF
add mapped point snake_logic/snake_body[18][2]/q snake_logic_snake_body_reg[18][2]/QN -type DFF DFF
add mapped point snake_logic/snake_body[20][0]/q snake_logic_snake_body_reg[20][0]/QN -type DFF DFF
add mapped point snake_logic/snake_body[20][1]/q snake_logic_snake_body_reg[20][1]/QN -type DFF DFF
add mapped point snake_logic/snake_body[2][0]/q snake_logic_snake_body_reg[2][0]/QN -type DFF DFF
add mapped point snake_logic/snake_body[20][5]/q snake_logic_snake_body_reg[20][5]/QN -type DFF DFF
add mapped point snake_logic/snake_body[4][0]/q snake_logic_snake_body_reg[4][0]/QN -type DFF DFF
add mapped point snake_logic/snake_body[4][1]/q snake_logic_snake_body_reg[4][1]/QN -type DFF DFF
add mapped point snake_logic/snake_body[2][4]/q snake_logic_snake_body_reg[2][4]/QN -type DFF DFF
add mapped point snake_logic/snake_body[23][3]/q snake_logic_snake_body_reg[23][3]/QN -type DFF DFF
add mapped point snake_logic/snake_body[20][4]/q snake_logic_snake_body_reg[20][4]/QN -type DFF DFF
add mapped point snake_logic/snake_body[23][4]/q snake_logic_snake_body_reg[23][4]/QN -type DFF DFF
add mapped point snake_logic/snake_body[20][3]/q snake_logic_snake_body_reg[20][3]/QN -type DFF DFF
add mapped point snake_logic/snake_body[54][2]/q snake_logic_snake_body_reg[54][2]/QN -type DFF DFF
add mapped point snake_logic/snake_body[36][5]/q snake_logic_snake_body_reg[36][5]/QN -type DFF DFF
add mapped point snake_logic/snake_body[62][2]/q snake_logic_snake_body_reg[62][2]/QN -type DFF DFF
add mapped point snake_logic/snake_body[36][2]/q snake_logic_snake_body_reg[36][2]/QN -type DFF DFF
add mapped point snake_logic/snake_body[62][5]/q snake_logic_snake_body_reg[62][5]/QN -type DFF DFF
add mapped point snake_logic/snake_body[60][4]/q snake_logic_snake_body_reg[60][4]/QN -type DFF DFF
add mapped point snake_logic/snake_body[38][2]/q snake_logic_snake_body_reg[38][2]/QN -type DFF DFF
add mapped point snake_logic/snake_body[44][4]/q snake_logic_snake_body_reg[44][4]/QN -type DFF DFF
add mapped point snake_logic/snake_body[60][0]/q snake_logic_snake_body_reg[60][0]/QN -type DFF DFF
add mapped point snake_logic/snake_body[38][1]/q snake_logic_snake_body_reg[38][1]/QN -type DFF DFF
add mapped point snake_logic/snake_body[46][2]/q snake_logic_snake_body_reg[46][2]/QN -type DFF DFF
add mapped point snake_logic/snake_body[58][2]/q snake_logic_snake_body_reg[58][2]/QN -type DFF DFF
add mapped point snake_logic/snake_body[34][4]/q snake_logic_snake_body_reg[34][4]/QN -type DFF DFF
add mapped point snake_logic/snake_body[48][0]/q snake_logic_snake_body_reg[48][0]/QN -type DFF DFF
add mapped point snake_logic/snake_body[44][0]/q snake_logic_snake_body_reg[44][0]/QN -type DFF DFF
add mapped point snake_logic/snake_body[48][2]/q snake_logic_snake_body_reg[48][2]/QN -type DFF DFF
add mapped point snake_logic/snake_body[54][5]/q snake_logic_snake_body_reg[54][5]/QN -type DFF DFF
add mapped point snake_logic/snake_body[42][4]/q snake_logic_snake_body_reg[42][4]/QN -type DFF DFF
add mapped point snake_logic/snake_body[42][0]/q snake_logic_snake_body_reg[42][0]/QN -type DFF DFF
add mapped point snake_logic/snake_body[52][0]/q snake_logic_snake_body_reg[52][0]/QN -type DFF DFF
add mapped point snake_logic/snake_body[62][3]/q snake_logic_snake_body_reg[62][3]/QN -type DFF DFF
add mapped point snake_logic/snake_body[48][4]/q snake_logic_snake_body_reg[48][4]/QN -type DFF DFF
add mapped point snake_logic/snake_body[62][4]/q snake_logic_snake_body_reg[62][4]/QN -type DFF DFF
add mapped point snake_logic/snake_body[62][1]/q snake_logic_snake_body_reg[62][1]/QN -type DFF DFF
add mapped point snake_logic/snake_body[62][0]/q snake_logic_snake_body_reg[62][0]/QN -type DFF DFF
add mapped point snake_logic/snake_body[48][3]/q snake_logic_snake_body_reg[48][3]/QN -type DFF DFF
add mapped point snake_logic/snake_body[48][5]/q snake_logic_snake_body_reg[48][5]/QN -type DFF DFF
add mapped point snake_logic/snake_body[50][0]/q snake_logic_snake_body_reg[50][0]/QN -type DFF DFF
add mapped point snake_logic/snake_body[50][1]/q snake_logic_snake_body_reg[50][1]/QN -type DFF DFF
add mapped point snake_logic/snake_body[50][3]/q snake_logic_snake_body_reg[50][3]/QN -type DFF DFF
add mapped point snake_logic/snake_body[50][4]/q snake_logic_snake_body_reg[50][4]/QN -type DFF DFF
add mapped point snake_logic/snake_body[50][5]/q snake_logic_snake_body_reg[50][5]/QN -type DFF DFF
add mapped point snake_logic/snake_body[52][1]/q snake_logic_snake_body_reg[52][1]/QN -type DFF DFF
add mapped point snake_logic/snake_body[52][2]/q snake_logic_snake_body_reg[52][2]/QN -type DFF DFF
add mapped point snake_logic/snake_body[52][3]/q snake_logic_snake_body_reg[52][3]/QN -type DFF DFF
add mapped point snake_logic/snake_body[52][5]/q snake_logic_snake_body_reg[52][5]/QN -type DFF DFF
add mapped point snake_logic/snake_body[54][0]/q snake_logic_snake_body_reg[54][0]/QN -type DFF DFF
add mapped point snake_logic/snake_body[54][1]/q snake_logic_snake_body_reg[54][1]/QN -type DFF DFF
add mapped point snake_logic/snake_body[54][3]/q snake_logic_snake_body_reg[54][3]/QN -type DFF DFF
add mapped point snake_logic/snake_body[54][4]/q snake_logic_snake_body_reg[54][4]/QN -type DFF DFF
add mapped point snake_logic/snake_body[58][0]/q snake_logic_snake_body_reg[58][0]/QN -type DFF DFF
add mapped point snake_logic/snake_body[58][1]/q snake_logic_snake_body_reg[58][1]/QN -type DFF DFF
add mapped point snake_logic/snake_body[58][4]/q snake_logic_snake_body_reg[58][4]/QN -type DFF DFF
add mapped point snake_logic/snake_body[58][3]/q snake_logic_snake_body_reg[58][3]/QN -type DFF DFF
add mapped point snake_logic/snake_body[60][1]/q snake_logic_snake_body_reg[60][1]/QN -type DFF DFF
add mapped point snake_logic/snake_body[60][2]/q snake_logic_snake_body_reg[60][2]/QN -type DFF DFF
add mapped point snake_logic/snake_body[60][3]/q snake_logic_snake_body_reg[60][3]/QN -type DFF DFF
add mapped point snake_logic/snake_body[60][5]/q snake_logic_snake_body_reg[60][5]/QN -type DFF DFF
add mapped point snake_logic/shift_done/q snake_logic_shift_done_reg/QN -type DFF DFF
add mapped point snake_logic/snake_body[46][0]/q snake_logic_snake_body_reg[46][0]/QN -type DFF DFF
add mapped point snake_logic/snake_body[46][1]/q snake_logic_snake_body_reg[46][1]/QN -type DFF DFF
add mapped point snake_logic/snake_body[46][3]/q snake_logic_snake_body_reg[46][3]/QN -type DFF DFF
add mapped point snake_logic/snake_body[46][4]/q snake_logic_snake_body_reg[46][4]/QN -type DFF DFF
add mapped point snake_logic/snake_body[46][5]/q snake_logic_snake_body_reg[46][5]/QN -type DFF DFF
add mapped point snake_logic/snake_body[50][2]/q snake_logic_snake_body_reg[50][2]/QN -type DFF DFF
add mapped point snake_logic/snake_body[34][5]/q snake_logic_snake_body_reg[34][5]/QN -type DFF DFF
add mapped point snake_logic/snake_body[48][1]/q snake_logic_snake_body_reg[48][1]/QN -type DFF DFF
add mapped point snake_logic/snake_body[42][5]/q snake_logic_snake_body_reg[42][5]/QN -type DFF DFF
add mapped point snake_logic/snake_body[44][1]/q snake_logic_snake_body_reg[44][1]/QN -type DFF DFF
add mapped point snake_logic/snake_body[44][2]/q snake_logic_snake_body_reg[44][2]/QN -type DFF DFF
add mapped point snake_logic/snake_body[36][0]/q snake_logic_snake_body_reg[36][0]/QN -type DFF DFF
add mapped point snake_logic/snake_body[34][1]/q snake_logic_snake_body_reg[34][1]/QN -type DFF DFF
add mapped point snake_logic/snake_body[36][1]/q snake_logic_snake_body_reg[36][1]/QN -type DFF DFF
add mapped point snake_logic/snake_body[36][3]/q snake_logic_snake_body_reg[36][3]/QN -type DFF DFF
add mapped point snake_logic/snake_body[36][4]/q snake_logic_snake_body_reg[36][4]/QN -type DFF DFF
add mapped point snake_logic/snake_body[52][4]/q snake_logic_snake_body_reg[52][4]/QN -type DFF DFF
add mapped point snake_logic/snake_body[38][0]/q snake_logic_snake_body_reg[38][0]/QN -type DFF DFF
add mapped point snake_logic/snake_body[38][4]/q snake_logic_snake_body_reg[38][4]/QN -type DFF DFF
add mapped point snake_logic/snake_body[38][5]/q snake_logic_snake_body_reg[38][5]/QN -type DFF DFF
add mapped point snake_logic/snake_body[38][3]/q snake_logic_snake_body_reg[38][3]/QN -type DFF DFF
add mapped point snake_logic/snake_body[42][1]/q snake_logic_snake_body_reg[42][1]/QN -type DFF DFF
add mapped point snake_logic/snake_body[42][3]/q snake_logic_snake_body_reg[42][3]/QN -type DFF DFF
add mapped point snake_logic/snake_body[42][2]/q snake_logic_snake_body_reg[42][2]/QN -type DFF DFF
add mapped point snake_logic/snake_body[44][3]/q snake_logic_snake_body_reg[44][3]/QN -type DFF DFF
add mapped point snake_logic/snake_body[44][5]/q snake_logic_snake_body_reg[44][5]/QN -type DFF DFF
add mapped point snake_logic/snake_body[34][3]/q snake_logic_snake_body_reg[34][3]/QN -type DFF DFF
add mapped point snake_logic/snake_body[34][2]/q snake_logic_snake_body_reg[34][2]/QN -type DFF DFF
add mapped point snake_logic/snake_body[34][0]/q snake_logic_snake_body_reg[34][0]/QN -type DFF DFF
add mapped point snake_logic/snake_body[22][1]/q snake_logic_snake_body_reg[22][1]/QN -type DFF DFF
add mapped point snake_logic/snake_body[22][5]/q snake_logic_snake_body_reg[22][5]/QN -type DFF DFF
add mapped point snake_logic/snake_body[22][2]/q snake_logic_snake_body_reg[22][2]/QN -type DFF DFF
add mapped point snake_logic/snake_body[22][3]/q snake_logic_snake_body_reg[22][3]/QN -type DFF DFF
add mapped point snake_logic/snake_body[22][0]/q snake_logic_snake_body_reg[22][0]/QN -type DFF DFF
add mapped point snake_logic/snake_body[22][4]/q snake_logic_snake_body_reg[22][4]/QN -type DFF DFF
add mapped point snake_logic/apple_location[1]/q snake_logic_apple_location_reg[1]/QN -type DFF DFF
add mapped point snake_logic/apple_location[5]/q snake_logic_apple_location_reg[5]/QN -type DFF DFF
add mapped point snake_logic/snake_body[0][2]/q snake_logic_snake_body_reg[0][2]/QN -type DFF DFF
add mapped point snake_logic/snake_body[0][0]/q snake_logic_snake_body_reg[0][0]/QN -type DFF DFF
add mapped point snake_logic/snake_body[0][5]/q snake_logic_snake_body_reg[0][5]/QN -type DFF DFF
add mapped point snake_logic/apple_location[2]/q snake_logic_apple_location_reg[2]/QN -type DFF DFF
add mapped point snake_logic/apple_location[0]/q snake_logic_apple_location_reg[0]/QN -type DFF DFF
add mapped point snake_logic/apple_location[3]/q snake_logic_apple_location_reg[3]/QN -type DFF DFF
add mapped point snake_logic/apple_location[4]/q snake_logic_apple_location_reg[4]/QN -type DFF DFF
add mapped point snake_logic/snake_body[0][4]/q snake_logic_snake_body_reg[0][4]/QN -type DFF DFF
add mapped point snake_logic/snake_body[0][3]/q snake_logic_snake_body_reg[0][3]/QN -type DFF DFF
add mapped point snake_logic/snake_body[0][1]/q snake_logic_snake_body_reg[0][1]/QN -type DFF DFF
add mapped point snake_logic/from_controller_temp[1]/q snake_logic_from_controller_temp_reg[1]/Q -type DFF DFF
add mapped point snake_controller/column_anode[4]/q snake_controller_column_anode_reg[4]/Q -type DFF DFF
add mapped point snake_controller/column_anode[7]/q snake_controller_column_anode_reg[7]/Q -type DFF DFF
add mapped point snake_controller/column_anode[6]/q snake_controller_column_anode_reg[6]/Q -type DFF DFF
add mapped point snake_controller/column_anode[1]/q snake_controller_column_anode_reg[1]/Q -type DFF DFF
add mapped point snake_controller/column_anode[5]/q snake_controller_column_anode_reg[5]/Q -type DFF DFF
add mapped point snake_controller/column_anode[0]/q snake_controller_column_anode_reg[0]/Q -type DFF DFF
add mapped point snake_controller/column_anode[2]/q snake_controller_column_anode_reg[2]/Q -type DFF DFF
add mapped point snake_controller/column_anode[3]/q snake_controller_column_anode_reg[3]/Q -type DFF DFF
add mapped point snake_controller/to_logic[1]/q snake_controller_to_logic_reg[1]/QN -type DFF DFF
add mapped point snake_controller/row_cathode[5]/q snake_controller_row_cathode_reg[5]/QN -type DFF DFF
add mapped point snake_controller/row_cathode[0]/q snake_controller_row_cathode_reg[0]/QN -type DFF DFF
add mapped point snake_controller/row_cathode[6]/q snake_controller_row_cathode_reg[6]/QN -type DFF DFF
add mapped point snake_controller/row_cathode[1]/q snake_controller_row_cathode_reg[1]/QN -type DFF DFF
add mapped point snake_controller/row_cathode[2]/q snake_controller_row_cathode_reg[2]/QN -type DFF DFF
add mapped point snake_controller/row_cathode[7]/q snake_controller_row_cathode_reg[7]/QN -type DFF DFF
add mapped point snake_controller/row_cathode[3]/q snake_controller_row_cathode_reg[3]/QN -type DFF DFF
add mapped point snake_controller/row_cathode[4]/q snake_controller_row_cathode_reg[4]/QN -type DFF DFF
add mapped point snake_logic/from_controller_temp[0]/q snake_logic_from_controller_temp_reg[0]/Q -type DFF DFF
add mapped point snake_controller/to_logic[0]/q snake_controller_to_logic_reg[0]/Q -type DFF DFF
add mapped point snake_controller/direction_state[0]/q snake_controller_direction_state_reg[0]/Q -type DFF DFF
add mapped point snake_controller/direction_state_next[0]/q snake_controller_direction_state_next_reg[0]/QN -type DFF DFF
add mapped point snake_controller/execution_state[1]/q snake_controller_execution_state_reg[1]/Q -type DFF DFF
add mapped point snake_controller/execution_state[0]/q snake_controller_execution_state_reg[0]/Q -type DFF DFF
add mapped point snake_logic/next_head_temp[3]/q snake_logic_next_head_temp_reg[3]/QN -type DFF DFF
add mapped point snake_controller/current_row[2]/q snake_controller_current_row_reg[2]/QN -type DFF DFF
add mapped point snake_logic/next_head_temp[5]/q snake_logic_next_head_temp_reg[5]/QN -type DFF DFF
add mapped point snake_controller/direction_state[1]/q snake_controller_direction_state_reg[1]/Q -type DFF DFF
add mapped point snake_controller/execution_state_next[0]/q snake_controller_execution_state_next_reg[0]/QN -type DFF DFF
add mapped point snake_controller/execution_state_next[1]/q snake_controller_execution_state_next_reg[1]/QN -type DFF DFF
add mapped point snake_logic/next_head_temp[4]/q snake_logic_next_head_temp_reg[4]/QN -type DFF DFF
add mapped point snake_controller/direction_state_next[1]/q snake_controller_direction_state_next_reg[1]/QN -type DFF DFF
add mapped point snake_logic/next_head_temp[2]/q snake_logic_next_head_temp_reg[2]/QN -type DFF DFF
add mapped point snake_controller/game_state[0]/q snake_controller_game_state_reg[0]/Q -type DFF DFF
add mapped point snake_controller/current_row[1]/q snake_controller_current_row_reg[1]/QN -type DFF DFF
add mapped point snake_prng/random_num[5]/q snake_prng_random_num_reg[5]/QN -type DFF DFF
add mapped point snake_prng/random_num[1]/q snake_prng_random_num_reg[1]/QN -type DFF DFF
add mapped point snake_prng/random_num[3]/q snake_prng_random_num_reg[3]/QN -type DFF DFF
add mapped point snake_controller/game_state[1]/q snake_controller_game_state_reg[1]/Q -type DFF DFF
add mapped point snake_prng/random_num[0]/q snake_prng_random_num_reg[0]/QN -type DFF DFF
add mapped point snake_controller/game_state_next[0]/q snake_controller_game_state_next_reg[0]/QN -type DFF DFF
add mapped point snake_controller/current_row[0]/q snake_controller_current_row_reg[0]/QN -type DFF DFF
add mapped point snake_prng/random_num[2]/q snake_prng_random_num_reg[2]/QN -type DFF DFF
add mapped point snake_prng/random_num[4]/q snake_prng_random_num_reg[4]/QN -type DFF DFF
add mapped point snake_logic/next_head_temp[1]/q snake_logic_next_head_temp_reg[1]/QN -type DFF DFF
add mapped point snake_controller/game_state_next[1]/q snake_controller_game_state_next_reg[1]/QN -type DFF DFF
add mapped point snake_logic/next_head_temp[0]/q snake_logic_next_head_temp_reg[0]/QN -type DFF DFF
add mapped point snake_logic/random_num_temp[0]/q snake_logic_random_num_temp_reg[0]/QN -type DFF DFF
add mapped point snake_logic/random_num_temp[1]/q snake_logic_random_num_temp_reg[1]/QN -type DFF DFF
add mapped point snake_prng/restart_temp/q snake_prng_restart_temp_reg/QN -type DFF DFF
add mapped point snake_logic/restart_temp/q snake_logic_restart_temp_reg/QN -type DFF DFF
add mapped point snake_prng/request_rand_temp/q snake_prng_request_rand_temp_reg/Q -type DFF DFF
add mapped point snake_logic/random_num_temp[5]/q snake_logic_random_num_temp_reg[5]/Q -type DFF DFF
add mapped point snake_logic/random_num_temp[3]/q snake_logic_random_num_temp_reg[3]/Q -type DFF DFF
add mapped point snake_logic/random_num_temp[4]/q snake_logic_random_num_temp_reg[4]/Q -type DFF DFF
add mapped point snake_logic/random_num_temp[2]/q snake_logic_random_num_temp_reg[2]/Q -type DFF DFF



//Black Boxes



//Empty Modules as Blackboxes
