#!/bin/sh

vlog ../../src/hydra/hydra_pkg.sv           \
     ../../src/hydra/hydra_arbiter.sv       \
     ../../src/hydra/hydra_scratchpad.sv    \
     ../../src/hydra/hydra_transform.sv     \
     hydra_tb.sv
vsim hydra_tb -do "log -r /*; add wave -r /*; run -all"